name: test-project-oc
services:
  db:
    container_name: test_db
    build:
      context: .
      dockerfile: db.dockerfile
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: test
    restart: unless-stopped
